### PR TITLE
introduce "envelope" class to instantiate MicroDAQ more easily

### PR DESCRIPTION
**Pull request by mhier**
New MicroDAQ class for more easy instantiation:
* Takes configuration directly from XML config file
* No need to deal with HDF5 vs. ROOT in application
* "Modern" ApplicationCore: No need to configure module after instantiation. Tag to search for and path name of trigger variable passed to constructor.

This should only add functionality and not destroy anything currently working.

### CODE REVIEW

**Comment by zenker** [comment]
So the question is if we should add an option to add tags to DeviceModule. Then we could use the envelope class also for DeviceModules....
In that case `addSource` would not be needed any more.

**Comment by mhier** [comment]
Does this PR break the use of `addSource()` without the envelope class for `DeviceModules`? If not, I would do this in a separate step and merge this for now as is. I prefer not to make too big changes at the same time right now...

**Comment by zenker** [comment]
No we can leave it as it is for now.
One question:
Is the trigger defined in this line used:
https://github.com/ChimeraTK/ApplicationCore-MicroDAQ/blob/cf320da064b85e5f50d6ed343a5b41f1091a5766/include/MicroDAQ.h#L213
I guess not and it can be removed....

**Comment by mhier** [comment]
> No we can leave it as it is for now.
> One question:
> Is the trigger defined in this line used:
> 
> https://github.com/ChimeraTK/ApplicationCore-MicroDAQ/blob/cf320da064b85e5f50d6ed343a5b41f1091a5766/include/MicroDAQ.h#L213
> 
> I guess not and it can be removed....

That was intended for backwards compatibility only (sorry, I forgot to add a comment). If applications connect to the trigger directly, they might expect the variable to be at that place. If we don't need this kind of compatibility, we can remove this.

**Pull request merged**
